SELECT ?drugLabel ?drug ?meshdrug ?unii ?diseaseLabel ?disease ?meshdisease

WHERE
{
   ?disease wdt:P2176 ?drug .
   OPTIONAL { ?drug wdt:P652 ?unii . }
   OPTIONAL { ?drug wdt:P486 ?meshdrug . }
   OPTIONAL { ?disease wdt:P486 ?meshdisease . }
   SERVICE wikibase:label {  bd:serviceParam wikibase:language "en, de" . }
}
ORDER BY ?drugLabel