-- Add Foreign Keys --
ALTER TABLE COREFERENCE ADD CONSTRAINT PMID_unqiue UNIQUE (PMID,ANA_START_INDEX,ANA_END_INDEX,ANT_START_INDEX,ANT_END_INDEX);

ALTER TABLE COREFERENCE ADD CONSTRAINT ANT_SENTENCE_ID_ibfk_5 UNIQUE (ANT_SENTENCE_ID);

ALTER TABLE COREFERENCE ADD CONSTRAINT ANA_SENTENCE_ID_ibfk_4 FOREIGN KEY (ANA_SENTENCE_ID) REFERENCES SENTENCE (SENTENCE_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE COREFERENCE ADD CONSTRAINT ANT_SENTENCE_ID_ibfk_5 FOREIGN KEY (ANT_SENTENCE_ID) REFERENCES SENTENCE (SENTENCE_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PREDICATION ADD CONSTRAINT PMID_ibfk_1 FOREIGN KEY (PMID) REFERENCES SENTENCE (PMID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PREDICATION ADD CONSTRAINT PREDICATION_ibfk_1 FOREIGN KEY (SENTENCE_ID) REFERENCES SENTENCE (SENTENCE_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PREDICATION ADD CONSTRAINT PREDICATION_AUX_ibfk_1 FOREIGN KEY (PREDICATION_ID) REFERENCES PREDICATION (PREDICATION_ID) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE SENTENCE ADD CONSTRAINT SENTENCE_ibfk_1 FOREIGN KEY (PMID) REFERENCES CITATIONS (PMID) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE SENTENCE ADD CONSTRAINT unique_sentence_id UNIQUE (PMID,TYPE,NUMBER);

-- ??
-- ALTER TABLE PREDICATION ADD CONSTRAINT PREDICATION_ibfk_2 FOREIGN KEY (PMID) REFERENCES SENTENCE (PMID) ON DELETE CASCADE ON UPDATE CASCADE;


--Given Indices --
CREATE INDEX pred_sentence_id_idx ON PREDICATION (SENTENCE_ID);
CREATE INDEX pred_pmid_btree_idx ON PREDICATION USING BTREE (PMID);


CREATE INDEX gencon_prefname_idx ON GENERIC_CONCEPT (PREFERRED_NAME);


CREATE INDEX predaux_predication_id_idx ON PREDICATION_AUX (PREDICATION_ID);


CREATE INDEX sentence_pmid_btree ON SENTENCE USING BTREE (PMID);
CREATE INDEX sentence_pmid_hash ON SENTENCE USING HASH (PMID);

-- Own Indices:
CREATE INDEX pred_subject_name_idx ON PREDICATION (SUBJECT_NAME);
CREATE INDEX pred_predicate_idx ON PREDICATION (PREDICATE);
CREATE INDEX pred_object_name_idx ON PREDICATION (OBJECT_NAME);

CREATE INDEX pred_subject_cui_idx ON PREDICATION (SUBJECT_CUI);
CREATE INDEX pred_object_cui_idx ON PREDICATION (OBJECT_CUI);


CREATE INDEX entity_sentence_id_idx ON ENTITY (SENTENCE_ID);


