version: '3'

volumes:
  narraint_postgres:
    external: true
  narraint_tmp:
    external: true

services:
  psql:
    image: "postgres:10.12-alpine"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - narraint_postgres:/var/lib/postgresql/data

  admin:
    image: "dockage/phppgadmin"
    depends_on:
      - psql
    environment:
      PHP_PG_ADMIN_SERVER_HOST: psql
    ports:
      - 8080:80

  narraint:
    image: "narraint:latest"
    depends_on:
      - "psql"
    environment:
      NI_POSTGRES_PW: example
    volumes:
      - /path/to/input:/input
      - /path/to/output:/output
      - narraint_tmp:/tmp
    command: -c COLLECTION -t DF C D

