#!/bin/bash
# $1 - document path
# $2 - document collection
# $3 - entity export
# $4 - relation export
TAG_CLEANING_SQL="/home/kroll/NarrativeIntelligence/sql/clean_tags.sql"
PREDICATION_CLEANING_SQL="/home/kroll/NarrativeIntelligence/sql/clean_predication.sql"

echo $1
echo $2
echo $3
echo $4

# Load everything
python3 ~/NarrativeAnnotation/src/narrant/backend/load_document.py $1 -c $2

# Next, tag the documents with our PharmDictTagger
python3 ~/NarrativeAnnotation/src/narrant/preprocessing/dictpreprocess.py -c $2 --skip-load --workers 15

# Execute Cleaning Rules for Tagging
echo 'cleaning Tag table with hand-written rules'
psql "host=127.0.0.1 port=5432 dbname=taggingdbtest user=tagginguser password=u3j4io1234u8-13!14" -f $TAG_CLEANING_SQL

# Perform pharmaceutical classification
#python3 ~/NarrativeAnnotation/src/narrant/preprocessing/classification.py -c $2 -r /home/kroll/NarrativeAnnotation/resources/classification/pharmaceutical_classification_rules.txt --cls Pharmaceutical -w 15 --skip-load

# Run GNormPlus
#python3 ~/NarrativeAnnotation/src/narrant/preprocessing/preprocess.py $1 -c $2 --skip-load --workers 3 --gnormplus
# Run TaggerOne
#python3 ~/NarrativeAnnotation/src/narrant/preprocessing/preprocess.py $1 -c $2 --skip-load --workers 2 --tagger-one

# exit

# Do the statement extraction for all $2 documents via our Pipeline
python3 ~/NarrativeIntelligence/src/narraint/extraction/pharmaceutical_pipeline.py -c $2 -et PathIE --workers 26 --relation_vocab /home/kroll/NarrativeIntelligence/resources/pharm_relation_vocab.json

# Do the canonicalizing step
python3 ~/KGExtractionToolbox/src/kgextractiontoolbox/cleaning/canonicalize_predicates.py -c $2 --word2vec_model /home/kroll/workingdir/BioWordVec_PubMed_MIMICIII_d200.bin --relation_vocab ~/NarrativeIntelligence/resources/pha$

# Apply the rules
python3 ~/NarrativeIntelligence/src/narraint/cleaning/pharmaceutical_rules.py -c $2

# Execute Cleaning Rules for Predications
echo 'cleaning predication table with hand-written rules'
psql "host=127.0.0.1 port=5432 dbname=taggingdbtest user=tagginguser password=u3j4io1234u8-13!14" -f $PREDICATION_CLEANING_SQL

# Export the entity annotations
python ~/KGExtractionToolbox/src/kgextractiontoolbox/entitylinking/export_annotations.py -d -t $3 --format json --collection $2

# Export the relations
python ~/KGExtractionToolbox/src/kgextractiontoolbox/extraction/export_predications.py $4 --collection $2 --format tsv --metadata --none-relations