#!/bin/bash
# $DOCUMENT_FILE - document path
# $DOCUMENT_COLLECTION - document collection

TAG_CLEANING_SQL="/home/kroll/NarrativeIntelligence/sql/clean_tags.sql"
PREDICATION_CLEANING_SQL="/home/kroll/NarrativeIntelligence/sql/clean_predication.sql"

DOCUMENT_FILE="/home/kroll/workingdir/cord19_fulltext_benchmark.json"
DOCUMENT_COLLECTION="CORD19"

# Load everything
python3 ~/NarrativeIntelligence/src/narraint/document/load_narrative_documents.py $DOCUMENT_FILE -c $DOCUMENT_COLLECTION

# Next, tag the documents with our PharmDictTagger
python3 ~/NarrativeAnnotation/src/narrant/preprocessing/dictpreprocess.py -c $DOCUMENT_COLLECTION --skip-load --workers 15 --sections

# Execute Cleaning Rules for Tagging
echo 'cleaning Tag table with hand-written rules'
psql "host=127.0.0.1 port=5432 dbname=fidpharmazie user=tagginguser password=u3j4io1234u8-13!14" -f $TAG_CLEANING_SQL

# Perform pharmaceutical classification
python3 ~/KGExtractionToolbox/src/kgextractiontoolbox/entitylinking/classification.py --sections -c $DOCUMENT_COLLECTION -r /home/kroll/NarrativeAnnotation/resources/classification/pharmaceutical_classification_rules.txt --cls Pharmaceutical -w 15 --skip-load
python3 ~/KGExtractionToolbox/src/kgextractiontoolbox/entitylinking/classification.py --sections -c $DOCUMENT_COLLECTION -r /home/kroll/NarrativeAnnotation/resources/classification/plant_specific_rules.txt --cls PlantSpecific -w 15 --skip-load


# Do the statement extraction for all $DOCUMENT_COLLECTION documents via our Pipeline
python3 ~/mining/NarrativeIntelligence/lib/NarrativeAnnotation/src/narrant/extraction/pharmaceutical_pipeline.py --sections -c $DOCUMENT_COLLECTION -et PathIE --workers 26 --relation_vocab /home/kroll/NarrativeIntelligence/resources/pharm_relation_vocab.json
