#!/bin/bash
FILES="$1/*.txt"
for f in $FILES
do
    echo "Tagging $f..."
    python3 ~/NarrativeIntelligence/narraint/preprocessing/preprocess.py $f "%f.tagged.pubtator" -c PubMed -t DF DR DC PF E --skip-load --workdir tmp --workers 20
done;

FILES="$1/*.pubtator"
for f in $FILES
do
    echo "Tagging $f..."
    python3 ~/NarrativeIntelligence/narraint/preprocessing/preprocess.py $f ""$f.tagged.pubtator" -c PubMed -t DF DR DC PF E --skip-load --workdir tmp --workers 20
done;