#!/bin/bash
ROOT_DIR="/hdd2/datasets/pubmed_medline/"
VACUUM_SQL="/home/kroll/NarrativeIntelligence/sql/vacuum_db.sql"
MEDLINE_BASELINE="/hdd2/datasets/pubmed_medline/2021_12/"
MEDLINE_UPDATES="/hdd2/datasets/pubmed_medline/2022_updates/"

cd $ROOT_DIR

# Load the Metadata
# Donwload the latest medline via wget -m ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/
# Download the latest updates via
# wget -m ftp://ftp.ncbi.nlm.nih.gov/pubmed/updatefiles -P $MEDLINE_UPDATES
# cp $MEDLINE_UPDATES/ftp.ncbi.nlm.nih.gov/pubmed/updatefiles/*.* $MEDLINE_UPDATES/.
# gunzip -f $MEDLINE_UPDATES/*.gz

# exit

# Unzip everything
python3 ~/NarrativeIntelligence/src/narraint/backend/load_pubmed_metadata.py $MEDLINE_UPDATES -c PubMed
# Load Baseline
# python3 ~/NarrativeIntelligence/src/narraint/backend/load_pubmed_metadata.py $MEDLINE_BASELINE -c PubMed


# Finally compute the new metadata service table2
python3 ~/NarrativeIntelligence/src/narraint/queryengine/prepare_metadata_for_service.py

# Compute reverse indexes
python3 ~/NarrativeIntelligence/src/narraint/queryengine/compute_reverse_index_predication.py
python3 ~/NarrativeIntelligence/src/narraint/queryengine/compute_reverse_index_tag.py

# Finally vacuum all tables
# Execute Cleaning Rules for Tagging
echo 'vacuum db tables...'
psql "host=127.0.0.1 port=5432 dbname=fidpharmazie user=tagginguser password=u3j4io1234u8-13!14" -f $VACUUM_SQL
